//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EmployeeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication1.EmployeeServiceReference.HelloWorldResponse HelloWorld(WebApplication1.EmployeeServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.HelloWorldResponse> HelloWorldAsync(WebApplication1.EmployeeServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name empID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListEmployee", ReplyAction="*")]
        WebApplication1.EmployeeServiceReference.ListEmployeeResponse ListEmployee(WebApplication1.EmployeeServiceReference.ListEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ListEmployeeResponse> ListEmployeeAsync(WebApplication1.EmployeeServiceReference.ListEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication1.EmployeeServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication1.EmployeeServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEmployee", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.ListEmployeeRequestBody Body;
        
        public ListEmployeeRequest() {
        }
        
        public ListEmployeeRequest(WebApplication1.EmployeeServiceReference.ListEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> deptID;
        
        public ListEmployeeRequestBody() {
        }
        
        public ListEmployeeRequestBody(string empID, string FullName, System.Nullable<int> deptID) {
            this.empID = empID;
            this.FullName = FullName;
            this.deptID = deptID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.ListEmployeeResponseBody Body;
        
        public ListEmployeeResponse() {
        }
        
        public ListEmployeeResponse(WebApplication1.EmployeeServiceReference.ListEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.EmployeeServiceReference.EmployeeInfo[] ListEmployeeResult;
        
        public ListEmployeeResponseBody() {
        }
        
        public ListEmployeeResponseBody(WebApplication1.EmployeeServiceReference.EmployeeInfo[] ListEmployeeResult) {
            this.ListEmployeeResult = ListEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : WebApplication1.EmployeeServiceReference.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.EmployeeServiceReference.EmployeeServiceSoap>, WebApplication1.EmployeeServiceReference.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.EmployeeServiceReference.HelloWorldResponse WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.HelloWorld(WebApplication1.EmployeeServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication1.EmployeeServiceReference.HelloWorldRequest inValue = new WebApplication1.EmployeeServiceReference.HelloWorldRequest();
            inValue.Body = new WebApplication1.EmployeeServiceReference.HelloWorldRequestBody();
            WebApplication1.EmployeeServiceReference.HelloWorldResponse retVal = ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.HelloWorldResponse> WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.HelloWorldAsync(WebApplication1.EmployeeServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WebApplication1.EmployeeServiceReference.HelloWorldRequest inValue = new WebApplication1.EmployeeServiceReference.HelloWorldRequest();
            inValue.Body = new WebApplication1.EmployeeServiceReference.HelloWorldRequestBody();
            return ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.EmployeeServiceReference.ListEmployeeResponse WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployee(WebApplication1.EmployeeServiceReference.ListEmployeeRequest request) {
            return base.Channel.ListEmployee(request);
        }
        
        public WebApplication1.EmployeeServiceReference.EmployeeInfo[] ListEmployee(string empID, string FullName, System.Nullable<int> deptID) {
            WebApplication1.EmployeeServiceReference.ListEmployeeRequest inValue = new WebApplication1.EmployeeServiceReference.ListEmployeeRequest();
            inValue.Body = new WebApplication1.EmployeeServiceReference.ListEmployeeRequestBody();
            inValue.Body.empID = empID;
            inValue.Body.FullName = FullName;
            inValue.Body.deptID = deptID;
            WebApplication1.EmployeeServiceReference.ListEmployeeResponse retVal = ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployee(inValue);
            return retVal.Body.ListEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ListEmployeeResponse> WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployeeAsync(WebApplication1.EmployeeServiceReference.ListEmployeeRequest request) {
            return base.Channel.ListEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ListEmployeeResponse> ListEmployeeAsync(string empID, string FullName, System.Nullable<int> deptID) {
            WebApplication1.EmployeeServiceReference.ListEmployeeRequest inValue = new WebApplication1.EmployeeServiceReference.ListEmployeeRequest();
            inValue.Body = new WebApplication1.EmployeeServiceReference.ListEmployeeRequestBody();
            inValue.Body.empID = empID;
            inValue.Body.FullName = FullName;
            inValue.Body.deptID = deptID;
            return ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployeeAsync(inValue);
        }
    }
}
