//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EmployeeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SearchModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        private System.Nullable<System.DateTime> BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BossIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BossID {
            get {
                return this.BossIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BossIDField, value) != true)) {
                    this.BossIDField = value;
                    this.RaisePropertyChanged("BossID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (ShowEmployeeList) of message ShowEmployeeList does not match the default value (ListEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowEmployeeList", ReplyAction="*")]
        WebApplication1.EmployeeServiceReference.ShowEmployeeList1 ListEmployee(WebApplication1.EmployeeServiceReference.ShowEmployeeList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowEmployeeList", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ShowEmployeeList1> ListEmployeeAsync(WebApplication1.EmployeeServiceReference.ShowEmployeeList request);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchEmployee) of message SearchEmployee does not match the default value (ListEmployee1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchEmployee", ReplyAction="*")]
        WebApplication1.EmployeeServiceReference.SearchEmployee1 ListEmployee1(WebApplication1.EmployeeServiceReference.SearchEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.SearchEmployee1> ListEmployee1Async(WebApplication1.EmployeeServiceReference.SearchEmployee request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowEmployeeList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ShowEmployeeList {
        
        public ShowEmployeeList() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowEmployeeListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ShowEmployeeList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.SearchModel[] ShowEmployeeListResult;
        
        public ShowEmployeeList1() {
        }
        
        public ShowEmployeeList1(WebApplication1.EmployeeServiceReference.SearchModel[] ShowEmployeeListResult) {
            this.ShowEmployeeListResult = ShowEmployeeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEmployee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchEmployee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EmployeeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FullName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<int> DepartmentID;
        
        public SearchEmployee() {
        }
        
        public SearchEmployee(string EmployeeID, string FullName, System.Nullable<int> DepartmentID) {
            this.EmployeeID = EmployeeID;
            this.FullName = FullName;
            this.DepartmentID = DepartmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEmployeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchEmployee1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.EmployeeServiceReference.SearchModel[] SearchEmployeeResult;
        
        public SearchEmployee1() {
        }
        
        public SearchEmployee1(WebApplication1.EmployeeServiceReference.SearchModel[] SearchEmployeeResult) {
            this.SearchEmployeeResult = SearchEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : WebApplication1.EmployeeServiceReference.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.EmployeeServiceReference.EmployeeServiceSoap>, WebApplication1.EmployeeServiceReference.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.EmployeeServiceReference.ShowEmployeeList1 WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployee(WebApplication1.EmployeeServiceReference.ShowEmployeeList request) {
            return base.Channel.ListEmployee(request);
        }
        
        public WebApplication1.EmployeeServiceReference.SearchModel[] ListEmployee() {
            WebApplication1.EmployeeServiceReference.ShowEmployeeList inValue = new WebApplication1.EmployeeServiceReference.ShowEmployeeList();
            WebApplication1.EmployeeServiceReference.ShowEmployeeList1 retVal = ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployee(inValue);
            return retVal.ShowEmployeeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ShowEmployeeList1> WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployeeAsync(WebApplication1.EmployeeServiceReference.ShowEmployeeList request) {
            return base.Channel.ListEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.ShowEmployeeList1> ListEmployeeAsync() {
            WebApplication1.EmployeeServiceReference.ShowEmployeeList inValue = new WebApplication1.EmployeeServiceReference.ShowEmployeeList();
            return ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.EmployeeServiceReference.SearchEmployee1 WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployee1(WebApplication1.EmployeeServiceReference.SearchEmployee request) {
            return base.Channel.ListEmployee1(request);
        }
        
        public WebApplication1.EmployeeServiceReference.SearchModel[] ListEmployee1(string EmployeeID, string FullName, System.Nullable<int> DepartmentID) {
            WebApplication1.EmployeeServiceReference.SearchEmployee inValue = new WebApplication1.EmployeeServiceReference.SearchEmployee();
            inValue.EmployeeID = EmployeeID;
            inValue.FullName = FullName;
            inValue.DepartmentID = DepartmentID;
            WebApplication1.EmployeeServiceReference.SearchEmployee1 retVal = ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployee1(inValue);
            return retVal.SearchEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.SearchEmployee1> WebApplication1.EmployeeServiceReference.EmployeeServiceSoap.ListEmployee1Async(WebApplication1.EmployeeServiceReference.SearchEmployee request) {
            return base.Channel.ListEmployee1Async(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.EmployeeServiceReference.SearchEmployee1> ListEmployee1Async(string EmployeeID, string FullName, System.Nullable<int> DepartmentID) {
            WebApplication1.EmployeeServiceReference.SearchEmployee inValue = new WebApplication1.EmployeeServiceReference.SearchEmployee();
            inValue.EmployeeID = EmployeeID;
            inValue.FullName = FullName;
            inValue.DepartmentID = DepartmentID;
            return ((WebApplication1.EmployeeServiceReference.EmployeeServiceSoap)(this)).ListEmployee1Async(inValue);
        }
    }
}
