//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public int DepartmentID { get; set; }
        public string BossID { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public string FullName
        {
            get
            {
                return (FirstName+" "+LastName);
            }
        }

    
        public virtual HR_Department HR_Department { get; set; }
    }
}
